### ISSUE TITLE
[enhancement] 希望可以增加一下 gpt api server 的配置项

### ISSUE THREAD

**Issue by palering** [eirueirufu/novel#20]
现在只看到了 `novel.openaiKey` 这一项配置,只能配置 key.
如果这个项目还继续维护话,可以支持下增加除了 `openai` 之外其他的提供商配置,
比如 `Azure` 和一些第三方的二道贩子, 理论上增加一个 apiServer 地址的配置就可以了

**Comment by eirueirufu** [comment]
非常感谢你的建议，gpt这部分确实有很多地方需要配置
